(* ::Package:: *)

(* ::Input:: *)
(*Explore Rewriting System Demo*)


(* ::InheritFromParent:: *)
(**)


(* ::Input:: *)
(*play with the System demo to find some pattern*)


(* ::Input:: *)
(*DynamicModule[*)
(**)
(*	{*)
(*		mat0 ={{1,1,1},{1,1,1},{1,1,1}},*)
(*		mat1 ={{0,1,0},{1,0,1},{0,1,0}}*)
(*	},*)
(**)
(*	Manipulate[*)
(**)
(*		Pane[*)
(*			Image[*)
(*				Nest[ArrayFlatten[#/.{0->mat0,1->mat1}]&,{{1}},i],*)
(*				ImageSize -> d*)
(*			],*)
(*			Dynamic[ dp] * 3^5 *)
(*			(* + 15, Scrollbars \[Rule] True *)*)
(*		],*)
(**)
(*		(* Hiding the pane selector *)*)
(*		{{dp,{1,1}, "Pane"},{{1,1}-> "Small",{3,1}-> "Wide",{3,2}-> "Large", {3,3}-> "Huge"}, None},*)
(**)
(*		{{d, 3^6, "Size"},3^5,3^6, Manipulator, ImageSize-> 220},*)
(*		{{i, 5,"Steps"},Range[6],Manipulator, ImageSize->220},*)
(**)
(*		(*(* Column Layout *)*)
(*		{{rule1,{{1,1,1},{1,0,1},{1,1,1}} ,Style["\[FilledSquare] \[Rule] ", 20]},0,1,{3,3}, MatrixSetter [##]&},*)
(*		{{rule2,{{1,1,1},{1,1,1},{1,1,1}} , Style["\[EmptySquare] \[Rule] ", 20]},0,1, {3,3}, MatrixSetter[##]&}, *)*)
(**)
(*		(* Row Layout *)*)
(*		Row[{*)
(*			Spacer[20],Style["\[FilledSquare] \[Rule] ", 20], MatrixSetter[Dynamic[mat0], {0,1, {3,3}}],*)
(*			Spacer[20], Style["\[EmptySquare] \[Rule] ", 20], MatrixSetter[Dynamic[mat1], {0,1, {3,3}}]*)
(*		}],*)
(**)
(*		ControlPlacement->Bottom,*)
(**)
(*		(* Let the user change the pane size via bookmarks *)*)
(*		Bookmarks-> { *)
(*			"Medium Pane":> (dp= {2,2}),*)
(*			"Large Pane":> (dp= {3,2})*)
(*		}*)
(*	]*)
(*]*)


(* ::Input:: *)
(*Create a new system demo?*)


(* ::Input:: *)
(*Attempt 1*)


(* ::Input:: *)
(*DynamicModule[*)
(**)
(*	{*)
(*		mat0 ={{1,1,1,1},{1,1,1,1},{1,1,1,1}, {1,1,1,1}, {1,1,1,1}},*)
(*		mat1 ={{0,1,0,0},{1,0,1,0},{0,1,0,0},{1,0,0,0}, {0,0,1,0}}*)
(*	},*)
(**)
(*	Manipulate[*)
(**)
(*		Pane[*)
(*			Image[*)
(*				Nest[ArrayFlatten[#/.{0->mat0,1->mat1}]&,{{1}},i],*)
(*				ImageSize -> d*)
(*			],*)
(*			Dynamic[ dp] * 3^5 *)
(*			(* + 15, Scrollbars \[Rule] True *)*)
(*		],*)
(**)
(*		(* Hiding the pane selector *)*)
(*		{{dp,{1,1}, "Pane"},{{1,1}-> "Small",{3,1}-> "Wide",{3,2}-> "Large", {3,3}-> "Huge"}, None},*)
(**)
(*		{{d, 3^6, "Size"},3^5,3^6, Manipulator, ImageSize-> 220},*)
(*		{{i, 5,"Steps"},Range[6],Manipulator, ImageSize->220},*)
(**)
(*		(*(* Column Layout *)*)
(*		{{rule1,{{1,1,1},{1,0,1},{1,1,1}} ,Style["\[FilledSquare] \[Rule] ", 20]},0,1,{3,3}, MatrixSetter [##]&},*)
(*		{{rule2,{{1,1,1},{1,1,1},{1,1,1}} , Style["\[EmptySquare] \[Rule] ", 20]},0,1, {3,3}, MatrixSetter[##]&}, *)*)
(**)
(*		(* Row Layout *)*)
(*		Row[{*)
(*			Spacer[20],Style["\[FilledSquare] \[Rule] ", 20], MatrixSetter[Dynamic[mat0], {0,1,{4,4}}],*)
(*			Spacer[20], Style["\[EmptySquare] \[Rule] ", 20], MatrixSetter[Dynamic[mat1], {0,1, {4,4}}]*)
(*		}],*)
(**)
(*		ControlPlacement->Bottom,*)
(**)
(*		(* Let the user change the pane size via bookmarks *)*)
(*		Bookmarks-> { *)
(*			"Medium Pane":> (dp= {2,2}),*)
(*			"Large Pane":> (dp= {3,2})*)
(*		}*)
(*	]*)
(*]*)


(* ::Input:: *)
(*attempt 2*)


(* ::Input:: *)
(*DynamicModule[*)
(**)
(*	{*)
(*		mat0 ={{2,1,1,1},{1,1,2,1},{1,1,1,2}, {1,2,1,1}, {1,2,1,1}},*)
(*		mat1 ={{0,1,0,0},{1,0,1,0},{0,1,0,0},{1,0,0,0}, {0,0,1,0}}*)
(*	},*)
(**)
(*	Manipulate[*)
(**)
(*		Pane[*)
(*			Image[*)
(*				Nest[ArrayFlatten[#/.{0->mat0,1->mat1}]&,{{1}},i],*)
(*				ImageSize -> d*)
(*			],*)
(*			Dynamic[ dp] * 3^5 *)
(*			(* + 15, Scrollbars \[Rule] True *)*)
(*		],*)
(**)
(*		(* Hiding the pane selector *)*)
(*		{{dp,{1,1}, "Pane"},{{1,1}-> "Small",{3,1}-> "Wide",{3,2}-> "Large", {3,3}-> "Huge"}, None},*)
(**)
(*		{{d, 3^6, "Size"},3^5,3^6, Manipulator, ImageSize-> 220},*)
(*		{{i, 5,"Steps"},Range[6],Manipulator, ImageSize->220},*)
(**)
(*		(*(* Column Layout *)*)
(*		{{rule1,{{1,1,1},{1,0,1},{1,1,1}} ,Style["\[FilledSquare] \[Rule] ", 20]},0,1,{3,3}, MatrixSetter [##]&},*)
(*		{{rule2,{{1,1,1},{1,1,1},{1,1,1}} , Style["\[EmptySquare] \[Rule] ", 20]},0,1, {3,3}, MatrixSetter[##]&}, *)*)
(**)
(*		(* Row Layout *)*)
(*		Row[{*)
(*			Spacer[20],Style["\[FilledSquare] \[Rule] ", 20], MatrixSetter[Dynamic[mat0], {0,1,2 {4,4}}],*)
(*			Spacer[20], Style["\[EmptySquare] \[Rule] ", 20], MatrixSetter[Dynamic[mat1], {0,1,2 {4,4}}]*)
(*		}],*)
(**)
(*		ControlPlacement->Bottom,*)
(**)
(*		(* Let the user change the pane size via bookmarks *)*)
(*		Bookmarks-> { *)
(*			"Medium Pane":> (dp= {2,2}),*)
(*			"Large Pane":> (dp= {3,2})*)
(*		}*)
(*	]*)
(*]*)


(* ::Input:: *)
(*attempt 3*)


(* ::Input:: *)
(*DynamicModule[*)
(**)
(*	{*)
(*		mat0 ={{1,1,1,1},{1,1,1,1},{1,1,1,1}, {1,1,1,1}, {1,1,1,1}},*)
(*		mat1 ={{0,1,0,0},{1,0,1,0},{0,1,0,0},{1,0,0,0}, {0,0,1,0}},*)
(*	mat2 ={{0,0,2,0},{0,0,0,2},{2,2,0,0},{0,2,0,0}, {0,2,2,0}}*)
(*	},*)
(**)
(*	Manipulate[*)
(**)
(*		Pane[*)
(*			Image[*)
(*				Nest[ArrayFlatten[#/.{0->mat0,1->mat1,2->mat2}]&,{{1}},i],*)
(*				ImageSize -> d*)
(*			],*)
(*			Dynamic[ dp] * 3^5 *)
(*			(* + 15, Scrollbars \[Rule] True *)*)
(*		],*)
(**)
(*		(* Hiding the pane selector *)*)
(*		{{dp,{1,1}, "Pane"},{{1,1}-> "Small",{3,1}-> "Wide",{3,2}-> "Large", {3,3}-> "Huge"}, None},*)
(**)
(*		{{d, 3^6, "Size"},3^5,3^6, Manipulator, ImageSize-> 220},*)
(*		{{i, 5,"Steps"},Range[6],Manipulator, ImageSize->220},*)
(**)
(*		(*(* Column Layout *)*)
(*		{{rule1,{{1,1,1},{1,0,1},{1,1,1}} ,Style["\[FilledSquare] \[Rule] ", 20]},0,1,{3,3}, MatrixSetter [##]&},*)
(*		{{rule2,{{1,1,1},{1,1,1},{1,1,1}} , Style["\[EmptySquare] \[Rule] ", 20]},0,1, {3,3}, MatrixSetter[##]&}, *)*)
(**)
(*		(* Row Layout *)*)
(*		Row[{*)
(*	Spacer[20],Style["\[FilledSquare] \[Rule] ", 20], MatrixSetter[Dynamic[mat0], {0,1{4,4}}],*)
(*	Spacer[20], Style["\[EmptySquare]  \[Rule] ", 20], MatrixSetter[Dynamic[mat1], {0,1 {4,4}}], Spacer[20],Style["0 \[Rule] ", 20], MatrixSetter[Dynamic[mat2], {0,2 {4,4}}]*)
(*		}],*)
(**)
(*		ControlPlacement->Bottom,*)
(**)
(*		(* Let the user change the pane size via bookmarks *)*)
(*		Bookmarks-> { *)
(*			"Medium Pane":> (dp= {2,2}),*)
(*			"Large Pane":> (dp= {3,2})*)
(*		}*)
(*	]*)
(*]*)
